export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOG_OUT = "LOG_OUT"
export const SHOW_MODAL_LOGIN = "SHOW_MODAL_LOGIN"
export const HIDE_MODAL_LOGIN = "HIDE_MODAL_LOGIN"
export const REFRESH_TOKEN_SUCCESS="REFRESH_TOKEN_SUCCESS"
export const SHOW_MODAL_SIGNIN="SHOW_MODAL_SIGNIN"
export const HIDE_MODAL_SIGNIN="HIDE_MODAL_SIGNIN"

export const SHOW_MODAL_FORGOT_PASS="SHOW_MODAL_FORGOT_PASS"
export const HIDE_MODAL_FORGOT_PASS="HIDE_MODAL_FORGOT_PASS"
export const SHOW_MODAL_PROFILE="SHOW_MODAL_PROFILE"
export const HIDE_MODAL_PROFILE="HIDE_MODAL_PROFILE"
export const CHANGE_AVATAR="CHANGE_AVATAR"
